name: traitar3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: conda env create
      run: |
        conda create -n traitar3 python=${{ matrix.python-version }} bioconda::hmmer scipy pandas numpy matplotlib
        conda activate traitar3
    - name: package install
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-dependency pytest-console-scripts
        python setup.py install
    - name: Test with pytest
      run: |
        pytest -s --script-launch-mode=subprocess
